# Generated by Django 4.2.6 on 2024-12-07 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='booking_date',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
    ]
